import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  header: { backgroundColor: '#0a2b5c', padding: 16, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', elevation: 4 },
  headerTitle: { color: 'white', fontSize: 20, fontWeight: '700' },
  headerButton: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  headerButtonText: { color: 'white', fontSize: 16 },
  main: { flex: 1, padding: 20 },
  personCard: { backgroundColor: 'white', borderRadius: 12, overflow: 'hidden', elevation: 5, marginBottom: 16 },
  personImage: { width: '100%', height: 200 },
  personInfo: { padding: 16 },
  personName: { fontSize: 18, fontWeight: 'bold', color: '#0a2b5c' },
  personDetail: { fontSize: 14, color: '#555' },
  formContainer: { backgroundColor: 'white', padding: 24, borderRadius: 12, elevation: 6 },
  formTitle: { fontSize: 24, fontWeight: 'bold', color: '#0a2b5c', textAlign: 'center', marginBottom: 24 },
  input: { borderWidth: 1, borderColor: '#ccc', borderRadius: 8, padding: 14, fontSize: 16, marginBottom: 16 },
  button: { padding: 16, borderRadius: 8, alignItems: 'center', marginTop: 8 },
  buttonPrimary: { backgroundColor: '#0a2b5c' },
  buttonSuccess: { backgroundColor: '#2d6a4f' },
  buttonText: { color: 'white', fontSize: 16, fontWeight: '600' },
  title: { fontSize: 32, fontWeight: 'bold', color: '#0a2b5c', textAlign: 'center', marginBottom: 24 },
  detailImage: { width: '100%', height: 300, borderRadius: 12, marginBottom: 16 },
  detailTitle: { fontSize: 28, fontWeight: 'bold', color: '#0a2b5c', marginBottom: 16 },
  detailText: { fontSize: 18, marginBottom: 12 },
  detailLabel: { fontWeight: 'bold', color: '#0a2b5c' },
  adminGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-around', gap: 16, marginTop: 24 },
  adminCard: { backgroundColor: 'white', padding: 32, borderRadius: 12, alignItems: 'center', elevation: 5, width: '45%' },
  adminCardTitle: { marginTop: 16, fontSize: 18, fontWeight: 'bold', color: '#0a2b5c' },
});